plugins { id 'com.android.application' }

android {
    namespace 'com.bridgelive.callassist'
    compileSdk 35

    defaultConfig {
        applicationId 'com.bridgelive.callassist'
        minSdk 26
        targetSdk 34
        versionCode 6
        versionName '0.6.0-honor'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
